### ISSUE TITLE
create_dlp_job() got an unexpected keyword argument 'job_id'

### ISSUE THREAD

**Issue by dwilliams782** [googleapis/python-dlp#78]
#23 ## Environment details

  - OS type and version: `Ubuntu 18.04`
  - Python version: `3.9.0`
  - pip version: `pip 20.2.4`
  - `google-cloud-dlp` version: `2.0.0`

#### Steps to reproduce

  1. Create a new dlp job calling `create_dlp_job()` and pass it as job_id as described in the docs [here](https://googleapis.dev/python/dlp/latest/gapic/v2/api.html).

Taken from the docs:

```
create_dlp_job(parent, inspect_job=None, risk_job=None, job_id=None, location_id=None, retry=<object object>, timeout=<object object>, metadata=None)
```

#### Code example

```python
    request = dlp_client.create_dlp_job(
                parent=PARENT,
                inspect_job=inspect_job_config,
                job_id=f"{project}_{dataset}_{table}_{get_current_timestamp()}"
            )
```

#### Stack trace
```
>>> result=create_job(project=project,dataset=dataset,table=table,rowsLimit=10)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "<path>/main.py", line 45, in create_job
    request = dlp_client.create_dlp_job(
TypeError: create_dlp_job() got an unexpected keyword argument 'job_id'
```

Sorry if I am missing something here but I can't see `job_id` in master or 2.0.0 but I have no idea how it would be present in the auto generated docs? Is there a different way of specifying a job id?

**Comment by dwilliams782** [comment]
So the docs are actually showing source for `1.0.0` where `job_id` **is** present. Where are the docs for 2.0.0?
